/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CpdAvatar {
        /**
          * ID for generating hash colours
         */
        "idName"?: string;
        /**
          * The name (first initial used as default)
         */
        "name": string;
        /**
          * The avatar's rendering type
         */
        "renderingType"?: "round" | "square";
        /**
          * The avatar's size
         */
        "size": string;
        /**
          * The avatar's source
         */
        "src"?: string;
    }
}
declare global {
    interface HTMLCpdAvatarElement extends Components.CpdAvatar, HTMLStencilElement {
    }
    var HTMLCpdAvatarElement: {
        prototype: HTMLCpdAvatarElement;
        new (): HTMLCpdAvatarElement;
    };
    interface HTMLElementTagNameMap {
        "cpd-avatar": HTMLCpdAvatarElement;
    }
}
declare namespace LocalJSX {
    interface CpdAvatar {
        /**
          * ID for generating hash colours
         */
        "idName"?: string;
        /**
          * The name (first initial used as default)
         */
        "name"?: string;
        /**
          * The avatar's rendering type
         */
        "renderingType"?: "round" | "square";
        /**
          * The avatar's size
         */
        "size"?: string;
        /**
          * The avatar's source
         */
        "src"?: string;
    }
    interface IntrinsicElements {
        "cpd-avatar": CpdAvatar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cpd-avatar": LocalJSX.CpdAvatar & JSXBase.HTMLAttributes<HTMLCpdAvatarElement>;
        }
    }
}
